### ISSUE TITLE
Add conditional for "a blade in one hand and have other hand free"

### ISSUE THREAD

**Issue by dta5003** [mdekrey/foundryvtt-dndmashup#16]
See Swordmage Warding: https://4e.dekrey.net/legacy/rule/ID_FMP_CLASS_53

AC bonus based on what's equipped at the time, isn't something that applies when attacking but when being attacked.

**Comment by mdekrey** [comment]
Due to the way the data is stored, for this one condition it is easier to handle the actual condition rather than provide a set of checkboxes like the attack roll conditions.
